FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Runnin restore before publish seems to cause some problems with NuGet package Fractions not being available...
# TODO: Figure out... ;)
# COPY *.csproj ./
# RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "k8s.demos.crd.azuredns.controller.dll"]