apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurednscredentials.demos.fearofoblivion.com
spec:
  scope: Cluster
  group: demos.fearofoblivion.com
  names:
    plural: azurednscredentials
    singular: azurednscredential
    kind: AzureDnsCredential
    shortNames:
    - adc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "A set of credentials to access Azure DNS"
          properties:
            spec:
              type: object
              properties:
                resourceGroup:
                  type: string
                dnsZone:
                  type: string
                subscriptionId:
                  type: string
                tenantId:
                  type: string
                clientId:
                  type: string
                clientSecret:
                  type: string