apiVersion: demos.fearofoblivion.com/v1
kind: DnsRecordset
metadata:
  name: demo.zerokoll.com
spec:
  dnsZone: zerokoll.com
  aRecords:
    - name: dnsdemo
      ttlSecs: 3600
      ipAddresses:
        - 127.0.0.1
  txtRecords:
    - name: dnsdemo
      values: 
        - Hello world!
        - Hello world again!
  cnameRecords:
    - name: dns
      alias: dnsdemo.zerokoll.com